spring.application.name=farmer-backend
server.port=8080

# File upload
file.upload-dir=C:/uploads
upload.folder=C:/uploads
max.upload.size=10485760
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.base-url=http://localhost:8080

# JWT
jwt.secret=your-secret-key-change-this-in-prod
jwt.expiration=86400000

# CORS
cors.allowed.origins=http://localhost:5173
